import { useState } from 'react'
import { Project } from '@/types'
import { api } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Download, Share2, Loader2 } from 'lucide-react'

const TOKEN = 'dev-token'

interface DownloadCardProps {
  project: Project
}

function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onloadend = () => {
      const result = reader.result as string
      resolve(result.split(',')[1])
    }
    reader.onerror = reject
    reader.readAsDataURL(blob)
  })
}

export default function DownloadCard({ project }: DownloadCardProps) {
  const [downloading, setDownloading] = useState(false)

  const handleDownload = async () => {
    setDownloading(true)
    try {
      const downloadUrl = await api.files.downloadUrl(project.id)
      const response = await fetch(downloadUrl, {
        headers: { Authorization: `Bearer ${TOKEN}` },
      })
      const blob = await response.blob()

      const isCapacitor = typeof window !== 'undefined' && (window as any).Capacitor

      if (isCapacitor) {
        const { Filesystem, Directory } = await import('@capacitor/filesystem')
        const base64 = await blobToBase64(blob)
        await Filesystem.writeFile({
          path: `${project.name}.zip`,
          data: base64,
          directory: Directory.Documents,
        })
      } else {
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `${project.name}.zip`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
      }
    } catch (e) {
      console.error('Download failed:', e)
    } finally {
      setDownloading(false)
    }
  }

  const handleShare = async () => {
    try {
      const isCapacitor = typeof window !== 'undefined' && (window as any).Capacitor
      if (!isCapacitor) return

      const { Share } = await import('@capacitor/share')
      const { Filesystem, Directory } = await import('@capacitor/filesystem')

      const fileUri = await Filesystem.getUri({
        path: `${project.name}.zip`,
        directory: Directory.Documents,
      })

      await Share.share({
        title: `${project.name}.zip`,
        text: 'Generated by OpenCode Mobile Cloud',
        url: fileUri.uri,
      })
    } catch (e) {
      console.error('Share failed:', e)
    }
  }

  return (
    <div className="bg-card border border-border rounded-lg p-3">
      <div className="flex items-start justify-between">
        <div>
          <p className="font-medium text-sm">{project.name}</p>
          {project.zipSize && (
            <p className="text-[10px] text-muted-foreground mt-0.5">
              {Math.round(project.zipSize / 1024)} KB
            </p>
          )}
        </div>
        <span className="text-[10px] text-green-400 bg-green-400/10 px-1.5 py-0.5 rounded">
          Ready
        </span>
      </div>
      <div className="flex gap-2 mt-3">
        <Button
          onClick={handleDownload}
          disabled={downloading}
          size="sm"
          className="bg-primary hover:bg-primary/90 gap-1.5 h-8"
        >
          {downloading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
          Download
        </Button>
        <Button onClick={handleShare} size="sm" variant="outline" className="gap-1.5 h-8">
          <Share2 className="h-3.5 w-3.5" />
          Share
        </Button>
      </div>
    </div>
  )
}
